### App Push 알람 테스트
POST http://localhost:8080/api/alarm
Content-Type: application/json

{
  "token": "IIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDORa7Ptk2Wyu6r",
  "title": "test",
  "body": "test"
}

### App Push Token 저장 테스트
POST http://localhost:8080/api/token
Content-Type: application/json

{
  "userId": 1,
  "token": "IIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDORa7Ptk2Wyu6r"
}